BEGIN TRANSACTION
GO
CREATE TABLE dbo.Countries
	(
	Id int NOT NULL IDENTITY (1, 1),
	[Name] varchar(200) NOT NULL,
	Region varchar(50) NOT NULL,
	Priority int null
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Countries ADD CONSTRAINT
	PK_Countries PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Countries SET (LOCK_ESCALATION = TABLE)
GO
COMMIT