insert into Countries (Name, Region) values ('Andorra','Europe')
insert into Countries (Name, Region) values ('United Arab Emirates','Middle east')
insert into Countries (Name, Region) values ('Afghanistan','Asia & Pacific')
insert into Countries (Name, Region) values ('Antigua and Barbuda','South/Latin America')
insert into Countries (Name, Region) values ('Anguilla','South/Latin America')
insert into Countries (Name, Region) values ('Albania','Europe')
insert into Countries (Name, Region) values ('Armenia','Europe')
insert into Countries (Name, Region) values ('Netherlands Antilles','South/Latin America')
insert into Countries (Name, Region) values ('Angola','Africa')
insert into Countries (Name, Region) values ('Antarctica','Asia & Pacific')
insert into Countries (Name, Region) values ('Argentina','South/Latin America')
insert into Countries (Name, Region) values ('American Samoa','Asia & Pacific')
insert into Countries (Name, Region) values ('Austria','Europe')
insert into Countries (Name, Region) values ('Australia','Asia & Pacific')
insert into Countries (Name, Region) values ('Aruba','South/Latin America')
insert into Countries (Name, Region) values ('Azerbaijan','Asia & Pacific')
insert into Countries (Name, Region) values ('Bosnia and Herzegovina','Europe')
insert into Countries (Name, Region) values ('Barbados','South/Latin America')
insert into Countries (Name, Region) values ('Bangladesh','Asia & Pacific')
insert into Countries (Name, Region) values ('Belgium','Europe')
insert into Countries (Name, Region) values ('Burkina Faso','Africa')
insert into Countries (Name, Region) values ('Bulgaria','Europe')
insert into Countries (Name, Region) values ('Bahrain','Arab States')
insert into Countries (Name, Region) values ('Burundi','Africa')
insert into Countries (Name, Region) values ('Benin','Africa')
insert into Countries (Name, Region) values ('Bermuda','North America')
insert into Countries (Name, Region) values ('Brunei Darussalam','Asia & Pacific')
insert into Countries (Name, Region) values ('Bolivia','South/Latin America')
insert into Countries (Name, Region) values ('Brazil','South/Latin America')
insert into Countries (Name, Region) values ('Bahamas','South/Latin America')
insert into Countries (Name, Region) values ('Bhutan','Asia & Pacific')
insert into Countries (Name, Region) values ('Bouvet Island','South/Latin America')
insert into Countries (Name, Region) values ('Botswana','Africa')
insert into Countries (Name, Region) values ('Belarus','Europe')
insert into Countries (Name, Region) values ('Belize','South/Latin America')
insert into Countries (Name, Region) values ('Canada','North America')
insert into Countries (Name, Region) values ('Cocos (Keeling) Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Congo, The Democratic Republic of the','Africa')
insert into Countries (Name, Region) values ('Central African Republic','Africa')
insert into Countries (Name, Region) values ('Congo','Africa')
insert into Countries (Name, Region) values ('Switzerland','Europe')
insert into Countries (Name, Region) values ('Côte D''Ivoire','Africa')
insert into Countries (Name, Region) values ('Cook Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Chile','South/Latin America')
insert into Countries (Name, Region) values ('Cameroon','Africa')
insert into Countries (Name, Region) values ('China','Asia & Pacific')
insert into Countries (Name, Region) values ('Colombia','South/Latin America')
insert into Countries (Name, Region) values ('Costa Rica','South/Latin America')
insert into Countries (Name, Region) values ('Cuba','South/Latin America')
insert into Countries (Name, Region) values ('Cape Verde','Africa')
insert into Countries (Name, Region) values ('Christmas Island','Asia & Pacific')
insert into Countries (Name, Region) values ('Cyprus','Europe')
insert into Countries (Name, Region) values ('Czech Republic','Europe')
insert into Countries (Name, Region) values ('Germany','Europe')
insert into Countries (Name, Region) values ('Djibouti','Arab States')
insert into Countries (Name, Region) values ('Denmark','Europe')
insert into Countries (Name, Region) values ('Dominica','South/Latin America')
insert into Countries (Name, Region) values ('Dominican Republic','South/Latin America')
insert into Countries (Name, Region) values ('Algeria','Arab States')
insert into Countries (Name, Region) values ('Ecuador','South/Latin America')
insert into Countries (Name, Region) values ('Estonia','Europe')
insert into Countries (Name, Region) values ('Egypt','Middle east')
insert into Countries (Name, Region) values ('Western Sahara','Africa')
insert into Countries (Name, Region) values ('Eritrea','Africa')
insert into Countries (Name, Region) values ('Spain','Europe')
insert into Countries (Name, Region) values ('Ethiopia','Africa')
insert into Countries (Name, Region) values ('Finland','Europe')
insert into Countries (Name, Region) values ('Fiji','Asia & Pacific')
insert into Countries (Name, Region) values ('Falkland Islands (Malvinas)','South/Latin America')
insert into Countries (Name, Region) values ('Micronesia, Federated States of','Asia & Pacific')
insert into Countries (Name, Region) values ('Faroe Islands','Europe')
insert into Countries (Name, Region) values ('France','Europe')
insert into Countries (Name, Region) values ('France, Metropolitan','Europe')
insert into Countries (Name, Region) values ('Gabon','Africa')
insert into Countries (Name, Region) values ('United Kingdom','Europe')
insert into Countries (Name, Region) values ('Grenada','South/Latin America')
insert into Countries (Name, Region) values ('Georgia','Europe')
insert into Countries (Name, Region) values ('French Guiana','South/Latin America')
insert into Countries (Name, Region) values ('Ghana','Africa')
insert into Countries (Name, Region) values ('Gibraltar','Europe')
insert into Countries (Name, Region) values ('Greenland','Europe')
insert into Countries (Name, Region) values ('Gambia','Africa')
insert into Countries (Name, Region) values ('Guinea','Africa')
insert into Countries (Name, Region) values ('Guadeloupe','South/Latin America')
insert into Countries (Name, Region) values ('Equatorial Guinea','Africa')
insert into Countries (Name, Region) values ('Greece','Europe')
insert into Countries (Name, Region) values ('South Georgia and the South Sandwich Islands','South/Latin America')
insert into Countries (Name, Region) values ('Guatemala','South/Latin America')
insert into Countries (Name, Region) values ('Guam','Asia & Pacific')
insert into Countries (Name, Region) values ('Guinea-Bissau','Africa')
insert into Countries (Name, Region) values ('Guyana','South/Latin America')
insert into Countries (Name, Region) values ('Hong Kong','Asia & Pacific')
insert into Countries (Name, Region) values ('Heard Island and McDonald Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Honduras','South/Latin America')
insert into Countries (Name, Region) values ('Croatia','Europe')
insert into Countries (Name, Region) values ('Haiti','South/Latin America')
insert into Countries (Name, Region) values ('Hungary','Europe')
insert into Countries (Name, Region) values ('Indonesia','Asia & Pacific')
insert into Countries (Name, Region) values ('Ireland','Europe')
insert into Countries (Name, Region) values ('Israel','Europe')
insert into Countries (Name, Region) values ('India','Asia & Pacific')
insert into Countries (Name, Region) values ('British Indian Ocean Territory','Asia & Pacific')
insert into Countries (Name, Region) values ('Iraq','Middle east')
insert into Countries (Name, Region) values ('Iran, Islamic Republic of','Middle east')
insert into Countries (Name, Region) values ('Iceland','Europe')
insert into Countries (Name, Region) values ('Italy','Europe')
insert into Countries (Name, Region) values ('Jamaica','South/Latin America')
insert into Countries (Name, Region) values ('Jordan','Middle east')
insert into Countries (Name, Region) values ('Japan','Asia & Pacific')
insert into Countries (Name, Region) values ('Kenya','Africa')
insert into Countries (Name, Region) values ('Kyrgyzstan','Asia & Pacific')
insert into Countries (Name, Region) values ('Cambodia','Asia & Pacific')
insert into Countries (Name, Region) values ('Kiribati','Asia & Pacific')
insert into Countries (Name, Region) values ('Comoros','Arab States')
insert into Countries (Name, Region) values ('Saint Kitts and Nevis','South/Latin America')
insert into Countries (Name, Region) values ('Korea, Democratic People''s Republic of','Asia & Pacific')
insert into Countries (Name, Region) values ('Korea, Republic of','Asia & Pacific')
insert into Countries (Name, Region) values ('Kuwait','Middle east')
insert into Countries (Name, Region) values ('Cayman Islands','South/Latin America')
insert into Countries (Name, Region) values ('Kazakhstan','Asia & Pacific')
insert into Countries (Name, Region) values ('Lao People''s Democratic Republic','Asia & Pacific')
insert into Countries (Name, Region) values ('Lebanon','Middle east')
insert into Countries (Name, Region) values ('Saint Lucia','South/Latin America')
insert into Countries (Name, Region) values ('Liechtenstein','Europe')
insert into Countries (Name, Region) values ('Sri Lanka','Asia & Pacific')
insert into Countries (Name, Region) values ('Liberia','Africa')
insert into Countries (Name, Region) values ('Lesotho','Africa')
insert into Countries (Name, Region) values ('Lithuania','Europe')
insert into Countries (Name, Region) values ('Luxembourg','Europe')
insert into Countries (Name, Region) values ('Latvia','Europe')
insert into Countries (Name, Region) values ('Libya','Middle east')
insert into Countries (Name, Region) values ('Morocco','Arab States')
insert into Countries (Name, Region) values ('Monaco','Europe')
insert into Countries (Name, Region) values ('Moldova, Republic of','Europe')
insert into Countries (Name, Region) values ('Madagascar','Africa')
insert into Countries (Name, Region) values ('Marshall Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Macedonia','Europe')
insert into Countries (Name, Region) values ('Mali','Africa')
insert into Countries (Name, Region) values ('Myanmar','Asia & Pacific')
insert into Countries (Name, Region) values ('Mongolia','Asia & Pacific')
insert into Countries (Name, Region) values ('Macau','Asia & Pacific')
insert into Countries (Name, Region) values ('Northern Mariana Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Martinique','South/Latin America')
insert into Countries (Name, Region) values ('Mauritania','Arab States')
insert into Countries (Name, Region) values ('Montserrat','South/Latin America')
insert into Countries (Name, Region) values ('Malta','Europe')
insert into Countries (Name, Region) values ('Mauritius','Africa')
insert into Countries (Name, Region) values ('Maldives','Asia & Pacific')
insert into Countries (Name, Region) values ('Malawi','Africa')
insert into Countries (Name, Region) values ('Mexico','South/Latin America')
insert into Countries (Name, Region) values ('Malaysia','Asia & Pacific')
insert into Countries (Name, Region) values ('Mozambique','Africa')
insert into Countries (Name, Region) values ('Namibia','Africa')
insert into Countries (Name, Region) values ('New Caledonia','Asia & Pacific')
insert into Countries (Name, Region) values ('Niger','Africa')
insert into Countries (Name, Region) values ('Norfolk Island','Asia & Pacific')
insert into Countries (Name, Region) values ('Nigeria','Africa')
insert into Countries (Name, Region) values ('Nicaragua','South/Latin America')
insert into Countries (Name, Region) values ('Netherlands','Europe')
insert into Countries (Name, Region) values ('Norway','Europe')
insert into Countries (Name, Region) values ('Nepal','Asia & Pacific')
insert into Countries (Name, Region) values ('Nauru','Asia & Pacific')
insert into Countries (Name, Region) values ('Niue','Asia & Pacific')
insert into Countries (Name, Region) values ('New Zealand','Asia & Pacific')
insert into Countries (Name, Region) values ('Oman','Middle east')
insert into Countries (Name, Region) values ('Panama','South/Latin America')
insert into Countries (Name, Region) values ('Peru','South/Latin America')
insert into Countries (Name, Region) values ('French Polynesia','Asia & Pacific')
insert into Countries (Name, Region) values ('Papua New Guinea','Asia & Pacific')
insert into Countries (Name, Region) values ('Philippines','Asia & Pacific')
insert into Countries (Name, Region) values ('Pakistan','Asia & Pacific')
insert into Countries (Name, Region) values ('Poland','Europe')
insert into Countries (Name, Region) values ('Saint Pierre and Miquelon','North America')
insert into Countries (Name, Region) values ('Pitcairn Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Puerto Rico','South/Latin America')
insert into Countries (Name, Region) values ('Palestinian Territory','Arab States')
insert into Countries (Name, Region) values ('Portugal','Europe')
insert into Countries (Name, Region) values ('Palau','Asia & Pacific')
insert into Countries (Name, Region) values ('Paraguay','South/Latin America')
insert into Countries (Name, Region) values ('Qatar','Middle east')
insert into Countries (Name, Region) values ('Reunion','Asia & Pacific')
insert into Countries (Name, Region) values ('Romania','Europe')
insert into Countries (Name, Region) values ('Russian Federation','Europe')
insert into Countries (Name, Region) values ('Rwanda','Africa')
insert into Countries (Name, Region) values ('Saudi Arabia','Middle east')
insert into Countries (Name, Region) values ('Solomon Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('Seychelles','Africa')
insert into Countries (Name, Region) values ('South Sudan','Africa')
insert into Countries (Name, Region) values ('Sudan','Arab States')
insert into Countries (Name, Region) values ('Sweden','Europe')
insert into Countries (Name, Region) values ('Singapore','Asia & Pacific')
insert into Countries (Name, Region) values ('Saint Helena','Africa')
insert into Countries (Name, Region) values ('Slovenia','Europe')
insert into Countries (Name, Region) values ('Svalbard and Jan Mayen','Europe')
insert into Countries (Name, Region) values ('Slovakia','Europe')
insert into Countries (Name, Region) values ('Sierra Leone','Africa')
insert into Countries (Name, Region) values ('San Marino','Europe')
insert into Countries (Name, Region) values ('Senegal','Africa')
insert into Countries (Name, Region) values ('Somalia','Arab States')
insert into Countries (Name, Region) values ('Suriname','South/Latin America')
insert into Countries (Name, Region) values ('Sao Tome and Principe','Africa')
insert into Countries (Name, Region) values ('El Salvador','South/Latin America')
insert into Countries (Name, Region) values ('Syrian Arab Republic','Asia & Pacific')
insert into Countries (Name, Region) values ('Swaziland','Africa')
insert into Countries (Name, Region) values ('Turks and Caicos Islands','South/Latin America')
insert into Countries (Name, Region) values ('Chad','Africa')
insert into Countries (Name, Region) values ('French Southern Territories','Asia & Pacific')
insert into Countries (Name, Region) values ('Togo','Africa')
insert into Countries (Name, Region) values ('Thailand','Asia & Pacific')
insert into Countries (Name, Region) values ('Tajikistan','Asia & Pacific')
insert into Countries (Name, Region) values ('Tokelau','Asia & Pacific')
insert into Countries (Name, Region) values ('Turkmenistan','Asia & Pacific')
insert into Countries (Name, Region) values ('Tunisia','Arab States')
insert into Countries (Name, Region) values ('Tonga','Asia & Pacific')
insert into Countries (Name, Region) values ('Timor-Leste','Asia & Pacific')
insert into Countries (Name, Region) values ('Turkey','Europe')
insert into Countries (Name, Region) values ('Trinidad and Tobago','South/Latin America')
insert into Countries (Name, Region) values ('Tuvalu','Asia & Pacific')
insert into Countries (Name, Region) values ('Taiwan','Asia & Pacific')
insert into Countries (Name, Region) values ('Tanzania, United Republic of','Africa')
insert into Countries (Name, Region) values ('Ukraine','Europe')
insert into Countries (Name, Region) values ('Uganda','Africa')
insert into Countries (Name, Region) values ('United States Minor Outlying Islands','Asia & Pacific')
insert into Countries (Name, Region) values ('United States','North America')
insert into Countries (Name, Region) values ('Uruguay','South/Latin America')
insert into Countries (Name, Region) values ('Uzbekistan','Asia & Pacific')
insert into Countries (Name, Region) values ('Holy See (Vatican City State)','Europe')
insert into Countries (Name, Region) values ('Saint Vincent and the Grenadines','South/Latin America')
insert into Countries (Name, Region) values ('Venezuela','South/Latin America')
insert into Countries (Name, Region) values ('Virgin Islands, British','South/Latin America')
insert into Countries (Name, Region) values ('Virgin Islands, U.S.','South/Latin America')
insert into Countries (Name, Region) values ('Vietnam','Asia & Pacific')
insert into Countries (Name, Region) values ('Vanuatu','Asia & Pacific')
insert into Countries (Name, Region) values ('Wallis and Futuna','Asia & Pacific')
insert into Countries (Name, Region) values ('Samoa','Asia & Pacific')
insert into Countries (Name, Region) values ('Yemen','Middle east')
insert into Countries (Name, Region) values ('Mayotte','Africa')
insert into Countries (Name, Region) values ('Serbia','Europe')
insert into Countries (Name, Region) values ('South Africa','Africa')
insert into Countries (Name, Region) values ('Zambia','Africa')
insert into Countries (Name, Region) values ('Montenegro','Europe')
insert into Countries (Name, Region) values ('Zimbabwe','Africa')
insert into Countries (Name, Region) values ('Aland Islands','Europe')
insert into Countries (Name, Region) values ('Guernsey','Europe')
insert into Countries (Name, Region) values ('Isle of Man','Europe')
insert into Countries (Name, Region) values ('Jersey','Europe')
insert into Countries (Name, Region) values ('Saint Barthelemy','South/Latin America')
insert into Countries (Name, Region) values ('Saint Martin','South/Latin America')
go

update Countries
set [Priority] = 0
where Region = 'South/Latin America'

go

update Countries
set [Priority] = 1
where Region = 'North America'

go

update Countries
set [Priority] = 2
where Region not in( 'North America', 'South/Latin America')